@startuml

    node n1
    node n2
    node n3
    node n4
    node n5
    
    n1 -- n2
    n2 -- n3
    n3 -- n4
    n4 -- n5
    n5 -- n1
    n2 -- n4


    node n10
    node n11
    node n12
    
    n10 -- n11
    n11 -- n12
    n10 -- n12



    node n20
    node n21
    node n22
    node n23
    
    n20 -- n21
    n21 -- n22
    n21 -- n23

@enduml