@startuml
digraph perfect_binary_tree {
    node [shape = box]
    20 -> 10
    20 -> 30
    10 -> 5
    10 -> 15
    30 -> 25
    30 -> 35
    5 -> 3
    5 -> 7
    15 -> 12
    15 -> 17
    25 -> 22
    25 -> 27
    35 -> 32
    35 -> 37
}
@enduml