@startuml
digraph binary_search_tree {
    node [shape = box]
    15 -> 8
    15 -> 25
    8 -> 4
    8 -> 12
    25 -> 20
    25 -> 30
    4 -> 2
    4 -> 6
    12 -> 10
    12 -> 14
    20 -> 17
    20 -> 22
    30 -> 27
    30 -> 35
}
@enduml