@startuml
digraph red_black_tree {
    node [shape = box]
    
    15 [label="15", style=filled, fillcolor=lightgray]
    8 [label="8", style=filled, fillcolor=pink]
    25 [label="25", style=filled, fillcolor=pink]
    4 [label="4", style=filled, fillcolor=lightgray]
    12 [label="12", style=filled, fillcolor=lightgray]
    20 [label="20", style=filled, fillcolor=lightgray]
    30 [label="30", style=filled, fillcolor=lightgray]
    2 [label="2", style=filled, fillcolor=pink]
    6 [label="6", style=filled, fillcolor=pink]
    
    15 -> 8
    15 -> 25
    8 -> 4
    8 -> 12
    25 -> 20
    25 -> 30
    4 -> 2
    4 -> 6
    
    subgraph cluster_legend {
        label = "Leyenda"
        node [shape = box, style=filled]
        legend_black [label="Negro", fillcolor=lightgray]
        legend_red [label="Rojo", fillcolor=pink]
    }
}
@enduml